import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import NavBar from '../components/navbar/Navbar'
import ProfileCard from '../components/cards/Profile'
import { useSelector } from 'react-redux'
import { selectTheme } from '../components/navbar/navThemeSlice'

interface pageProps {
  data: {
    avatar_url: string;
    bio: string;
  }
}

const Home: NextPage<pageProps> = ({ data }) => {
  return (
    <>
    <div data-theme={useSelector(selectTheme)}>
      <NavBar />
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={`${styles.main} h-screen`}>
        <ProfileCard image={data.avatar_url} about={data.bio} />
      </main>

      <footer className={styles.footer}>
      </footer>
    </div>
    </>
  )
}

export async function getStaticProps() {
  // call external Github Api
  const res = await fetch('https://api.github.com/users/wshivers93');
  const data = await res.json();

  console.log(data);

  return {
      props: {
          data,
      }
  }
}

export default Home
