import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import NavBar from '../components/navbar/Navbar'
import { useSelector } from 'react-redux'
import { selectTheme } from '../components/navbar/navThemeSlice'


const Home: NextPage = () => {
  return (
    <>
    <div data-theme={useSelector(selectTheme)}>
      <NavBar />
      <div className={styles.container}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={styles.main}>
          Main Content Here

          <div>
            Theme: {useSelector(selectTheme)};
          </div>
        </main>

        <footer className={styles.footer}>
        </footer>
      </div>
    </div>
    </>
  )
}

export default Home
