import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import NavBar from '../components/Navbar'

const Home: NextPage = () => {
  return (
    <>
    <NavBar />
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        Main Content Here
      </main>

      <footer className={styles.footer}>
      </footer>
    </div>
    </>
  )
}

export default Home
